SELECT 
	'IF NOT EXISTS (SELECT 1 FROM DuesCycles WHERE DuesCycles.CYCLE_NAME = ''' + DuesCycles.CYCLE_NAME + ''')' + CHAR(13) + CHAR(10) + 
	'    INSERT INTO DuesCycles (CYCLE_NAME, REPORT_FORM, MEM_TYPES, CATEGORIES, PRODUCT_CODES, INCLUDE_INACTIVE_MEMBERS, INCLUDE_SUSPENDED_MEMBERS, INCLUDE_INACTIVE_SECTIONS, INCLUDE_ZERO_BALANCE, MAJOR_SORT, MEMBER_SORT, PRODUCT_SORT, INITIAL_BILL_TITLE, INITIAL_BILL_TEXT, INITIAL_BILL_ADDRESS, INITIAL_BILL_END, FIRST_REMINDER_TITLE, FIRST_REMINDER_TEXT, FIRST_REMINDER_ADDRESS, FIRST_REMINDER_START, FIRST_REMINDER_END, SECOND_REMINDER_TITLE, SECOND_REMINDER_TEXT, SECOND_REMINDER_ADDRESS, SECOND_REMINDER_START, SECOND_REMINDER_END, INITIAL_BILL_START, FORCE_ADD_OTHER, INCLUDE_ALL_SECTIONS, INCLUDE_ALL_CHAPTERS, INCLUDE_ALL_MEM_ITEMS, BILL_CYCLE, ACCOUNTING_METHOD, MASS_BILL_ACCT_METH, UPDATE_COMP_AT_PAY, IS_FOR_JOIN, IS_FOR_RENEW) VALUES (' +  
	'''' + REPLACE(CYCLE_NAME,'''','''''') + ''',' + 
	'''' + REPORT_FORM + ''',' + 
	'''' + MEM_TYPES + ''',' + 
	'''' + CATEGORIES + ''',' + 
	'''' + REPLACE(CAST(PRODUCT_CODES AS varchar(MAX)),'''','''''') + ''',' + 
	CAST(INCLUDE_INACTIVE_MEMBERS AS varchar(1)) + ',' + 
	CAST(INCLUDE_SUSPENDED_MEMBERS AS varchar(1)) + ',' + 
	CAST(INCLUDE_INACTIVE_SECTIONS AS varchar(1)) + ',' + 
	CAST(INCLUDE_ZERO_BALANCE AS varchar(1)) + ',' + 
	CAST(MAJOR_SORT AS varchar(3)) + ',' + 
	CAST(MEMBER_SORT AS varchar(1)) + ',' + 
	CAST(PRODUCT_SORT AS varchar(1)) + ',' + 
	'''' + REPLACE(INITIAL_BILL_TITLE,'''','''''') + ''',' + 
	'''' + REPLACE(CAST(ISNULL(INITIAL_BILL_TEXT,'') AS varchar(MAX)),'''','''''') + ''',' + 
	CAST(INITIAL_BILL_ADDRESS AS varchar(10)) + ',' + 
	CAST(INITIAL_BILL_END AS varchar(10)) + ',' + 
	'''' + REPLACE(FIRST_REMINDER_TITLE,'''','''''') + ''',' + 
	'''' + REPLACE(CAST(ISNULL(FIRST_REMINDER_TEXT,'') AS varchar(MAX)),'''','''''') + ''',' + 
	CAST(FIRST_REMINDER_ADDRESS AS varchar(10)) + ',' + 
	CAST(FIRST_REMINDER_START AS varchar(10)) + ',' + 
	CAST(FIRST_REMINDER_END AS varchar(10)) + ',' + 
	'''' + REPLACE(SECOND_REMINDER_TITLE,'''','''''') + ''',' + 
	'''' + REPLACE(CAST(ISNULL(SECOND_REMINDER_TEXT,'') AS varchar(MAX)),'''','''''') + ''',' + 
	CAST(SECOND_REMINDER_ADDRESS AS varchar(10)) + ',' + 
	CAST(SECOND_REMINDER_START AS varchar(10)) + ',' + 
	CAST(SECOND_REMINDER_END AS varchar(10)) + ',' + 
	CAST(INITIAL_BILL_START AS varchar(10)) + ',' + 
	CAST(FORCE_ADD_OTHER AS varchar(1)) + ',' + 
	CAST(INCLUDE_ALL_SECTIONS AS varchar(1)) + ',' + 
	CAST(INCLUDE_ALL_CHAPTERS AS varchar(1)) + ',' + 
	CAST(INCLUDE_ALL_MEM_ITEMS AS varchar(1)) + ',' + 
	'''' + REPLACE(BILL_CYCLE,'''','''''') + ''',' + 
	'''' + REPLACE(ACCOUNTING_METHOD,'''','''''') + ''',' + 
	'''' + REPLACE(MASS_BILL_ACCT_METH,'''','''''') + ''',' + 
	CAST(UPDATE_COMP_AT_PAY AS varchar(1)) + ',' + 
	CAST(IS_FOR_JOIN AS varchar(1)) + ',' + 
	CAST(IS_FOR_RENEW AS varchar(1)) + ');' 
FROM 
	DuesCycles 
WHERE 
	CYCLE_NAME = 'ProHacViceRenewal';
