CREATE PROCEDURE [dbo].[BSI_GET_PRODUCT_TAX]
  @ID INT,
  @PRODUCT_CODE VARCHAR(25),
  @TAX_AMOUNT MONEY OUTPUT
AS
BEGIN
	--DECLARE VARIABLES
	DECLARE @PROVINCE AS VARCHAR(5)
	DECLARE @TAXRATE AS MONEY

	--GET USERS PROVINCE
	SET @PROVINCE = (SELECT STATE_PROVINCE FROM Name_Address WHERE PURPOSE = 'PRIMARY ADDRESS' AND ID = @ID)

	--GET TAX RATE FOR THE USER
	SET @TAXRATE = (SELECT
					CASE WHEN OTHER_AUTHORITY_1 = '' THEN TAX_RATE 
					ELSE 
						(SELECT T.TAX_RATE FROM PRODUCT_TAX AS T WHERE T.PRODUCT_CODE = CONCAT('TAX/',T1.OTHER_AUTHORITY_1))
					END
				FROM PRODUCT_TAX T1 WHERE PRODUCT_CODE = CONCAT('TAX/',@PROVINCE))

	--GET PRODUCT TAX AMOUNT
	SET @TAX_AMOUNT = (SELECT PRICE_1*(@TAXRATE/100) FROM PRODUCT WHERE PRODUCT_CODE = @PRODUCT_CODE)
	RETURN

END
GO
